repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: check-ast
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-merge-conflict
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "v2.6.2" # Use the sha or tag you want to point at
      hooks:
          - id: prettier
            args: ["--tab-width", "4", "--use-tabs"]
            additional_dependencies:
                - prettier@2.1.2
