name: Deploy Heroku

on:
    push:
        branches:
            - devel
jobs:
    build-deploy:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 4
        steps:
            - uses: actions/checkout@v2
            - name: Login to Heroku Container registry
              env:
                  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
              run: heroku container:login
            - name: Build, push and release
              env:
                  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
              run: |
                  docker build -f Dockerfile.prod -t registry.heroku.com/repositorium-easy-study/web .
                  docker push registry.heroku.com/repositorium-easy-study/web .
                  heroku container:release -a repositorium-easy-study web
